# Generated by Django 5.0.2 on 2024-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('amount', models.CharField(max_length=90)),
                ('payment_id', models.CharField(max_length=90)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
